export const SET_ASSAY_TYPE = [
  '10XscRNAseq',
  '10XsNucRNAseq',
  '10XscVDJ',
  '10XVisium',
  'ATACseq',
  'CutTag',
  'ChIPseq',
  'CutRun',
  'RNAseq',
  'WES',
  'WGS',
  'SLAMseq',
  'GeoMX',
]

export const OBJ_ORGANISMS_TYPE = {
  PRIMARY: ['Homo_sapiens', 'Mus_musculus', 'NA'],
  SECONDARY: [
    'Danio_rerio',
    'Drosophila_melanogaster',
    'Mustela_putorius_furo',
    'Anas_platyrhynchos',
    'Rattus_norvegicus',
    'Saccharomyces_cerevisiae',
    'Chlorocebus_sabaeus',
    'Schizosaccharomyces_pombe',
  ],
  HYBRID: [
    'Homo_sapiens-Drosophila_melanogaster',
    'Homo_sapiens-Escherichia_coli',
    'Homo_sapiens-Mus_musculus',
    'Homo_sapiens-Mus_musculus-Saccharomyces_cerevisiae',
    'Homo_sapiens-Saccharomyces_cerevisiae',
    'Mus_musculus-Drosophila_melanogaster',
    'Mus_musculus-Escherichia_coli',
    'Mus_musculus-Homo_sapiens',
    'Mus_musculus-Homo_sapiens-Drosophila_melanogaster',
    'Mus_musculus-Saccharomyces_cerevisiae',
  ],
  RDNA: ['Homo_sapiens-rDNA', 'Mus_musculus-rDNA'],
}

export const OBJ_REFERENCE_TYPE = {
  Homo_sapiens: ['hg38', 'hg38GDC', 'hg38_tdTom', 'hg19', 'hg19b37'],
  Mus_musculus: ['mm10', 'mm9', 'mm10_CAGE_LOH'],
  Drosophila_melanogaster: ['dm6'],
  Danio_rerio: ['danRer11'],
  Mustela_putorius_furo: ['musFur1', 'musFur11'],
  Anas_platyrhynchos: ['ZJU1', 'ASM874695v1'],
  Rattus_norvegicus: ['rn6'],
  Saccharomyces_cerevisiae: ['sacCer3'],
  Schizosaccharomyces_pombe: ['ASM294v2'],
  Escherichia_coli: ['ASM584v2'],
  Chlorocebus_sabaeus: ['chlSab2'],
  'Homo_sapiens-Drosophila_melanogaster': ['hg38-dm6', 'hg19-dm6'],
  'Homo_sapiens-Escherichia_coli': ['hg38-ASM584v2', 'hg19-ASM584v2'],
  'Homo_sapiens-Mus_musculus': ['hg38-mm10', 'hg19-mm9'],
  'Homo_sapiens-Mus_musculus-Saccharomyces_cerevisiae': ['hg38-mm10-sacCer3', 'hg19-mm9-sacCer3'],
  'Homo_sapiens-Saccharomyces_cerevisiae': ['hg38-sacCer3', 'hg19-sacCer3'],
  'Homo_sapiens-rDNA': ['rDNA_hg38'],
  'Mus_musculus-Drosophila_melanogaster': ['mm10-dm6', 'mm9-dm6'],
  'Mus_musculus-Escherichia_coli': ['mm10-ASM584v2', 'mm9-ASM584v2'],
  'Mus_musculus-Homo_sapiens': ['mm10-hg38', 'mm9-hg19'],
  'Mus_musculus-Homo_sapiens-Drosophila_melanogaster': ['mm10-hg38-dm6', 'mm9-hg19-dm6'],
  'Mus_musculus-Saccharomyces_cerevisiae': ['mm10-sacCer3', 'mm9-sacCer3'],
  'Mus_musculus-rDNA': ['rDNA_mm39'],
}
